config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create]
  resources :certifications, path_names: { new: "new/:vacols_id" } do
    get 'pdf', on: :member
    get 'form9_pdf', on: :member
    post 'confirm', on: :member
  end

  resources :certification_cancellations, only: [:show, :create]

  scope path: "/dispatch" do
    get "/", to: redirect("/dispatch/establish-claim")
    get 'missing-decision', to: 'establish_claims#unprepared_tasks'
    patch 'employee-count/:count', to: 'establish_claims#update_employee_count'

    resources :establish_claims,
              path: "/establish-claim",
              task_type: :EstablishClaim,
              only: [:index, :show] do

      patch 'assign', on: :collection
      post 'perform', on: :member
      post 'assign-existing-end-product', on: :member
      post 'review-complete', on: :member
      post 'email-complete', on: :member
      post 'no-email-complete', on: :member
      get 'pdf', on: :member
      patch 'cancel', on: :member
      put 'update-appeal', on: :member
    end
  end

  resources :document, only: [] do
    patch 'set-label', on: :member
    patch 'mark-as-read', on: :member
  end

  scope path: "/decision" do
    get "/", to: redirect("/decision/review")

    resources :annotation,
              path: "/review/annotation",
              only: [:create, :destroy, :update],
              on: :member

    resources :review,
              path: "/review",
              only: [:index] do
      get 'pdf', on: :collection
      get 'show', on: :collection
    end
  end

  patch "certifications" => "certifications#create"

  namespace :admin do
    post "establish-claim", to: "establish_claims#create"
    get "establish-claim", to: "establish_claims#show"
  end

  resources :functions, only: :index
  patch '/functions/change', to: 'functions#change'

  resources :offices, only: :index

  get "health-check", to: "health_checks#show"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get 'whats-new' => 'whats_new#show'

  get 'certification/stats(/:interval)', to: 'certification_stats#show', as: 'certification_stats'
  get 'dispatch/stats', to: 'dispatch_stats#show', as: 'dispatch_stats'
  get 'stats', to: 'stats#show'

  get "styleguide", to: "styleguide#show"

  get 'help' => 'help#show'

  root 'help#show'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  get "unauthorized" => "application#unauthorized"

  %w( 404 500 ).each do |code|
    get code, :to => "errors#show", :status_code => code
  end

  namespace :test do
    if ENV["TEST_USER_ID"]
      resources :setup, only: [:index]
      post "setup-uncertify-appeal" => "setup#uncertify_appeal"
      post "setup-appeal-location-date-reset" => "setup#appeal_location_date_reset"
      get "setup-delete-test-data" => "setup#delete_test_data"
    end

    if ApplicationController.dependencies_faked?
      resources :users, only: [:index]
      post "/set-user/:id", to: "users#set_user", as: "set_user"
      post "/set-end-products", to: "users#set_end_products", as: 'set_end_products'
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include AASM

  belongs_to :user
  belongs_to :appeal

  validate :no_open_tasks_for_appeal, on: :create
  delegate :vbms_id, to: :appeal

  class MustImplementInSubclassError < StandardError; end
  class UserAlreadyHasTaskError < StandardError; end

  enum completion_status: {
    routed_to_arc: 0,
    canceled: 1,
    expired: 2,
    routed_to_ro: 3,
    assigned_existing_ep: 4,
    special_issue_emailed: 5,
    special_issue_vacols_routed: 7,

    # These statuses are not in use anymore
    special_issue_not_emailed: 6
  }

  # Use this to define status texts that don't properly titlize
  COMPLETION_STATUS_TEXT = {
    routed_to_arc: "Completed",
    assigned_existing_ep: "Assigned Existing EP"
  }.freeze

  REASSIGN_OLD_TASKS = [:EstablishClaim].freeze

  class << self
    def unassigned
      where(user_id: nil)
    end

    def unprepared
      where(aasm_state: "unprepared")
    end

    def assigned_not_completed
      to_complete.where.not(assigned_at: nil)
    end

    def newest_first(column = :created_at)
      order(column => :desc)
    end

    def oldest_first
      order(created_at: :asc)
    end

    def completed_today
      where(completed_at: DateTime.now.beginning_of_day.utc..DateTime.now.end_of_day.utc)
    end

    def completed_today_by_user(user_id)
      where(completed_at: DateTime.now.beginning_of_day.utc..DateTime.now.end_of_day.utc,
            user_id: user_id)
    end

    def to_complete
      where.not(aasm_state: "completed").where.not(aasm_state: "unprepared")
    end

    def completed
      where(aasm_state: "completed")
    end

    def to_complete_task_for_appeal(appeal)
      to_complete.where(appeal: appeal)
    end

    def tasks_completed_by_users(tasks)
      tasks.each_with_object({}) do |task, user_numbers|
        user_numbers[task.user.full_name] = (user_numbers[task.user.full_name] || 0) + 1
      end
    end
  end

  aasm do
    state :unprepared, initial: true
    state :unassigned, :assigned, :started, :reviewed, :completed

    ## The 'unprepared' state is being used for establish claim tasks to designate
    #  tasks attached to appeals that do not have decision documents. Tasks that are
    #  in this state cannot be assigned to users. All tasks are in this state
    #  immediately after creation.
    event :prepare do
      transitions from: :unprepared, to: :unassigned
    end

    event :assign do
      transitions from: :unassigned, to: :assigned, after: (proc do |*args|
        assign_user(*args)

        # Temporarily needed while there are tasks created that don't have claim establishments
        init_claim_establishment!
      end)
    end

    event :start do
      transitions from: :assigned, to: :started, after: :start_time
    end

    # The 'review' state is being used for establish claim tasks to designate that an
    # external action has been completed, and we want to the user to perform one more
    # action or review the external action. In the case of establish claim we're letting
    # them add a note to VBMS
    event :review do
      before { |*args| assign_review_attributes(*args) }

      transitions from: :started, to: :reviewed
    end

    event :complete do
      before { |*args| assign_completion_attribtues(*args) }

      transitions from: :reviewed, to: :completed
      transitions from: :started, to: :completed
    end
  end

  def assign_review_attributes(outgoing_reference_id: nil)
    assign_attributes(outgoing_reference_id: outgoing_reference_id)
  end

  def assign_completion_attribtues(status:, outgoing_reference_id: nil)
    assign_review_attributes(outgoing_reference_id: outgoing_reference_id) unless reviewed?

    assign_attributes(
      completed_at: Time.now.utc,
      completion_status: status
    )
  end

  def before_assign
    # Test hook for testing race conditions
  end

  def assign_user(user)
    fail(UserAlreadyHasTaskError) if user.tasks.to_complete.where(type: type).count > 0
    update!(
      user: user,
      assigned_at: Time.now.utc
    )
  end

  def start_time
    update!(started_at: Time.now.utc)
  end

  def prepare_with_decision!
    return false if appeal.decisions.empty?

    appeal.decisions.each(&:fetch_and_cache_document_from_vbms)

    prepare!
  end

  def cancel!(feedback = nil)
    transaction do
      update!(comment: feedback)
      complete!(status: :canceled)
    end
  end

  def expire!
    Task.transaction do
      review! if may_review?
      complete_and_recreate!(:expired)
    end
  end

  def complete_and_recreate!(status_code)
    transaction do
      complete!(status: status_code)
      self.class.create!(appeal_id: appeal_id, type: type)
    end
  end

  def progress_status
    if completed_at
      "Completed"
    elsif started_at
      "In Progress"
    elsif assigned_at
      "Not Started"
    else
      "Unassigned"
    end
  end

  def days_since_creation
    (Time.zone.now - created_at).to_i / 1.day
  end

  def completion_status_text
    completion_status ? (COMPLETION_STATUS_TEXT[completion_status.to_sym] || completion_status.titleize) : ""
  end

  def no_open_tasks_for_appeal
    if self.class.to_complete_task_for_appeal(appeal).count > 0
      errors.add(:appeal, "Uncompleted task already exists for this appeal")
    end
  end

  def attributes
    super.merge(type: type)
  end

  def to_hash_with_bgs_call
    serializable_hash(
      include: [:user, appeal: {
        include: [
          :pending_eps,
          :non_canceled_end_products_within_30_days,
          decisions: { methods: :received_at }
        ],
        methods: [
          :serialized_decision_date,
          :disposition,
          :veteran_name,
          :decision_type,
          :station_key,
          :regional_office_key,
          :issues
        ] }],
      methods: [:progress_status, :aasm_state]
    )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :verify_access, except: [:unprepared_tasks, :update_employee_count]
  before_action :verify_assigned_to_current_user, only: [:show, :pdf, :cancel]

  class TaskTypeMissingError < StandardError; end

  TASKS_PER_PAGE = 10

  def index
    @tasks_completed_today = Task.completed_today
    @remaining_count_today = Task.to_complete.count
    @completed_count_today = @tasks_completed_today.count
    @to_complete_count = Task.to_complete.count
    @tasks_completed_by_users = Task.tasks_completed_by_users(@tasks_completed_today)

    render index_template
  end

  def update_appeal
    task.appeal.update!(special_issues_params)
    render json: {}
  end

  def show
    start_task!

    return render "canceled" if task.canceled?
    return render "assigned_existing_ep" if task.assigned_existing_ep?
    return render "complete" if task.completed?

    # TODO: Reassess the best way to handle decision errors
    return render "no_decisions" if task.appeal.decisions.nil?
  end

  def pdf
    return redirect_to "/404" if task.appeal.decisions.nil? || task.appeal.decisions.size == 0
    decision_number = params[:decision_number].to_i
    return redirect_to "/404" if decision_number >= task.appeal.decisions.size || decision_number < 0
    decision = task.appeal.decisions[decision_number]
    send_file(decision.serve, type: "application/pdf", disposition: "inline")
  end

  def assign
    # Doesn't assign if user has a task of the same type already assigned.
    next_task = current_user_next_task
    return not_found unless next_task

    next_task.assign!(:assigned, current_user) if next_task.may_assign?

    render json: { next_task_id: next_task.id }
  end

  private

  def user_completed_today
    current_user ? Task.completed_today_by_user(current_user.id).count : 0
  end
  helper_method :user_completed_today

  def to_complete_count
    Task.to_complete.count
  end
  helper_method :to_complete_count

  def current_user_historical_tasks
    current_user.tasks.completed.newest_first.limit(10)
  end
  helper_method :current_user_historical_tasks

  # Before assigning the next task to the current user, we want to check and
  # verify they have the right sensitivity level to access that case. If they
  # don't, we skip it and move on to the next case
  def next_unassigned_task
    @next_unassigned_task ||= scoped_tasks.unassigned.to_complete.find do |task|
      task.appeal.can_be_accessed_by_current_user?
    end
  end
  helper_method :next_unassigned_task

  # This method returns the next task this user should work on. Either,
  # a previously assigned task that was never completed, or a new
  # unassigned task.
  def current_user_next_task
    current_user.tasks.to_complete.where(type: type).first || next_unassigned_task
  end
  helper_method :current_user_next_task

  def scoped_tasks
    Task.where(type: type).oldest_first
  end

  def type
    params[:task_type] || (task && task.type.to_sym)
  end

  def start_text
    type.to_s.titlecase
  end
  helper_method :start_text

  def task_id
    params[:id]
  end

  def task
    @task ||= Task.find(task_id)
  end
  helper_method :task

  def index_template
    prefix = manager? ? "manager" : "worker"
    "#{prefix}_index"
  end

  def task_roles
    User::TASK_TYPE_TO_ROLES[type] || fail(TaskTypeMissingError)
  end

  def manager?
    current_user.can?(task_roles[:manager])
  end

  def verify_access
    manager? || verify_authorized_roles(task_roles[:employee])
  end

  def verify_assigned_to_current_user
    verify_user(task.user)
  end

  def logo_name
    "Dispatch"
  end

  def verify_not_complete
    return true unless task.completed?
    render json: { error_code: "task_already_completed" }, status: 422
  end

  def cancel_feedback
    params.require(:feedback)
  end

  def start_task!
    # Future safeguard for when we give managers a show view
    # for a given task
    task.start! if current_user == task.user && task.may_start?
  end

  def special_issues_params
    params.require(:special_issues).permit(:contaminated_water_at_camp_lejeune,
                                           :dic_death_or_accrued_benefits_united_states,
                                           :education_gi_bill_dependents_educational_assistance_scholars,
                                           :foreign_claim_compensation_claims_dual_claims_appeals,
                                           :foreign_pension_dic_all_other_foreign_countries,
                                           :foreign_pension_dic_mexico_central_and_south_america_caribb,
                                           :hearing_including_travel_board_video_conference,
                                           :home_loan_guaranty, :incarcerated_veterans, :insurance,
                                           :manlincon_compliance, :mustard_gas, :national_cemetery_administration,
                                           :nonrating_issue, :pension_united_states, :private_attorney_or_agent,
                                           :radiation, :rice_compliance, :spina_bifida,
                                           :us_territory_claim_american_samoa_guam_northern_mariana_isla,
                                           :us_territory_claim_philippines,
                                           :us_territory_claim_puerto_rico_and_virgin_islands,
                                           :vamc, :vocational_rehab, :waiver_of_overpayment)
  end
end

app/views/tasks/assigned_existing_ep.html.erb
<% content_for :page_title do task.appeal.task_header end %>
<%= react_component('BaseContainer', props: {
    availableTasks: !!current_user_next_task,
    buttonText: start_text,
    checklist: ['Reviewed decision', 'Assigned existing EP to claim'],
    firstHeader: 'Congratulations!',
    page: 'EstablishClaimComplete',
    totalCasesCompleted: user_completed_today,
    employeeCount: Rails.cache.read('employee_count') || '0',
    totalCasesToComplete: to_complete_count,
    secondHeader: task.appeal.veteran_full_name + "'s claim (" + task.appeal.vbms_id + ') has been assigned an EP.'
}) %>

app/views/tasks/canceled.html.erb
<% content_for :page_title do task.appeal.task_header end %>

<%= react_component("BaseContainer", props: {
  availableTasks: !!current_user_next_task,
  buttonText: start_text,
  employeeCount: Rails.cache.read('employee_count') || '0',
  page: "EstablishClaimCancel",
  secondHeader: "We’ve recorded your explanation for halting the routing of claim " + task.appeal.vbms_id + ". It has been removed from the queue and must now be processed outside of Caseflow Dispatch.",
  totalCasesCompleted: user_completed_today,
  totalCasesToComplete: to_complete_count
}) %>

app/views/tasks/complete.html.erb
<% content_for :page_title do task.appeal.task_header end %>

<% second_header = task.appeal.veteran_full_name + "'s End Product (" + task.appeal.vbms_id + ') has been created.'
   second_header = task.appeal.veteran_full_name + "'s claim (" + task.appeal.vbms_id + ') has been processed' if task.special_issue_emailed? or task.special_issue_not_emailed? %>

<%= react_component("BaseContainer", props: {
    availableTasks: !!current_user_next_task,
    buttonText: start_text,
    checklist: task.actions_taken,
    firstHeader: "Success!",
    page: "EstablishClaimComplete",
    totalCasesCompleted: user_completed_today,
    employeeCount: Rails.cache.read('employee_count') || '0',
    totalCasesToComplete: to_complete_count,
    secondHeader: second_header
}) %>

app/views/tasks/index.html.erb
<div class="cf-app-segment cf-app-segment--alt">
<h1>Work Flow
<span class="cf-associated-header">
  <%= @completed_count %> cases processed today, <%= @to_complete_count %> in queue
</span>
</h1>

<%= render partial: 'list_of_tasks', locals: {title: 'Current', tasks: to_complete_tasks} %>
<hr />
<%= render partial: 'list_of_tasks', locals: {title: 'History', tasks: completed_tasks} %>
</div>

app/views/tasks/manager_index.html.erb
<%= react_component("BaseContainer", props: {
  page: "TasksManagerIndex",
  toCompleteCount: @to_complete_count,
  completedCountToday: @completed_count_today,
  employeeCount: Rails.cache.read('employee_count') || '0',
  tasksCompletedByUsers: @tasks_completed_by_users
}) %>

app/views/tasks/no_decisions.html.erb
<!-- TODO: Remove me when decisions are handled in task creation -->
<% content_for :page_title do task.appeal.task_header end %>

<div class="usa-alert usa-alert-error" role="alert">
  <div class="usa-alert-body">
    <h3 class="usa-alert-heading">No Decision</h3>
    <p class="usa-alert-text">
      There are no decision documents associated with this veteran for the range of the decision date (<%= task.appeal.decision_date.to_formatted_s(:short_date) %>). 

      Please make sure the decision document exists and try again or <%= link_to "cancel this claims establishment", cancel_task_path(task, feedback: "No decisions"), method: :patch %>.
    </p>
  </div>
</div>

app/views/tasks/show.html.erb
<% content_for :page_title do task.appeal.task_header end %>
<%= react_component("BaseContainer", props: {
  task: task.to_hash_with_bgs_call,
  pdfLink: pdf_establish_claim_path(id: task.id, time: Time.now.to_i),
  pdfjsLink: pdfjs.full_path(file: pdf_establish_claim_path(id: task.id, time: Time.now.to_i)),
  page: "EstablishClaim",
  regionalOfficeCities: VACOLS::RegionalOffice::CITIES
}) %>

app/views/tasks/unprepared_tasks.html.erb
<%= react_component("BaseContainer", props: {
    unpreparedTasks: @unprepared_tasks.map(&:to_hash),
    page: "UnpreparedTasksIndex"
}) %>

app/views/tasks/worker_index.html.erb
<%= react_component("BaseContainer", props: {
  page: "CaseWorkerIndex",
  availableTasks: !!current_user_next_task,
  buttonText: start_text,
  completedCountToday: @completed_count_today,
  currentUserHistoricalTasks: current_user_historical_tasks.map(&:to_hash),
  toCompleteCount: @to_complete_count,
  totalAssignedIssues: total_assigned_issues
}) %>