config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create]
  resources :certifications, path_names: { new: "new/:vacols_id" } do
    get 'pdf', on: :member
    get 'form9_pdf', on: :member
    post 'confirm', on: :member
  end

  resources :certification_cancellations, only: [:show, :create]

  scope path: "/dispatch" do
    get "/", to: redirect("/dispatch/establish-claim")
    get 'missing-decision', to: 'establish_claims#unprepared_tasks'
    patch 'employee-count/:count', to: 'establish_claims#update_employee_count'

    resources :establish_claims,
              path: "/establish-claim",
              task_type: :EstablishClaim,
              only: [:index, :show] do

      patch 'assign', on: :collection
      post 'perform', on: :member
      post 'assign-existing-end-product', on: :member
      post 'review-complete', on: :member
      post 'email-complete', on: :member
      post 'no-email-complete', on: :member
      get 'pdf', on: :member
      patch 'cancel', on: :member
      put 'update-appeal', on: :member
    end
  end

  resources :document, only: [] do
    patch 'set-label', on: :member
    patch 'mark-as-read', on: :member
  end

  scope path: "/decision" do
    get "/", to: redirect("/decision/review")

    resources :annotation,
              path: "/review/annotation",
              only: [:create, :destroy, :update],
              on: :member

    resources :review,
              path: "/review",
              only: [:index] do
      get 'pdf', on: :collection
      get 'show', on: :collection
    end
  end

  patch "certifications" => "certifications#create"

  namespace :admin do
    post "establish-claim", to: "establish_claims#create"
    get "establish-claim", to: "establish_claims#show"
  end

  resources :functions, only: :index
  patch '/functions/change', to: 'functions#change'

  resources :offices, only: :index

  get "health-check", to: "health_checks#show"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get 'whats-new' => 'whats_new#show'

  get 'certification/stats(/:interval)', to: 'certification_stats#show', as: 'certification_stats'
  get 'dispatch/stats', to: 'dispatch_stats#show', as: 'dispatch_stats'
  get 'stats', to: 'stats#show'

  get "styleguide", to: "styleguide#show"

  get 'help' => 'help#show'

  root 'help#show'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  get "unauthorized" => "application#unauthorized"

  %w( 404 500 ).each do |code|
    get code, :to => "errors#show", :status_code => code
  end

  namespace :test do
    if ENV["TEST_USER_ID"]
      resources :setup, only: [:index]
      post "setup-uncertify-appeal" => "setup#uncertify_appeal"
      post "setup-appeal-location-date-reset" => "setup#appeal_location_date_reset"
      get "setup-delete-test-data" => "setup#delete_test_data"
    end

    if ApplicationController.dependencies_faked?
      resources :users, only: [:index]
      post "/set-user/:id", to: "users#set_user", as: "set_user"
      post "/set-end-products", to: "users#set_end_products", as: 'set_end_products'
    end
  end
end

app/models/certification.rb
##
# Certification is responsible for aggregating the information
# and providing methods used to assist the certification of an
# appeal. It also acts as a record of appeals that are certified
# using Caseflow.
#
class Certification < ActiveRecord::Base
  has_one :certification_cancellation, dependent: :destroy

  def start!
    # if we haven't yet started the form8
    # or if we last updated it earlier than 48 hours ago,
    # refresh it with new data.
    if !form8 || form8.updated_at < 48.hours.ago
      @form8 ||= Form8.new(certification_id: id)
      @form8.assign_attributes_from_appeal(appeal)
      @form8.save!
    else
      form8.update_certification_date
    end

    update_attributes!(
      already_certified:   calculate_already_certified,
      vacols_data_missing: calculate_vacols_data_missing,
      nod_matching_at:     calculate_nod_matching_at,
      form9_matching_at:   calculate_form9_matching_at,
      soc_matching_at:     calculate_soc_matching_at,
      ssocs_required:      calculate_ssocs_required,
      ssocs_matching_at:   calculcate_ssocs_matching_at,
      form8_started_at:    (certification_status == :started) ? now : nil
    )

    certification_status
  end

  def to_hash
    serializable_hash(
      methods: :certification_status,
      include: [
        appeal: { methods:
       [:nod_match?,
        :nod_date,
        :soc_match?,
        :soc_date,
        :form9_match?,
        :form9_date,
        :documents_match?,
        :veteran_name,
        :vbms_id] }]
    )
  end

  def complete!(user_id)
    appeal.certify!
    update_attributes!(completed_at: Time.zone.now, user_id: user_id)
  end

  # VACOLS attributes
  def appeal
    @appeal ||= Appeal.find_or_create_by_vacols_id(vacols_id)
  end

  def form8
    @form8 ||= Form8.find_by(certification_id: id)
  end

  def time_to_certify
    return nil if !completed_at || !created_at
    completed_at - created_at
  end

  def self.completed
    where("completed_at IS NOT NULL")
  end

  def self.was_missing_doc
    was_missing_nod.or(was_missing_soc)
                   .or(was_missing_ssoc)
                   .or(was_missing_form9)
  end

  def self.was_missing_nod
    # allow 30 second lag just in case 'nod_matching_at' timestamp is a few seconds
    # greater than 'created_at' timestamp
    where(nod_matching_at: nil).or(where("nod_matching_at > created_at + INTERVAL '30 seconds'"))
  end

  def self.was_missing_soc
    where(soc_matching_at: nil).or(where("soc_matching_at > created_at + INTERVAL '30 seconds'"))
  end

  def self.was_missing_ssoc
    ssoc_required.where(ssocs_matching_at: nil).or(where("ssocs_matching_at > created_at + INTERVAL '30 seconds'"))
  end

  def self.was_missing_form9
    where(form9_matching_at: nil).or(where("form9_matching_at > created_at + INTERVAL '30 seconds'"))
  end

  def self.ssoc_required
    where(ssocs_required: true)
  end

  def certification_status
    if appeal.certified?
      :already_certified
    elsif appeal.missing_certification_data?
      :data_missing
    elsif !appeal.documents_match?
      :mismatched_documents
    else
      :started
    end
  end

  private

  def now
    @now ||= Time.zone.now
  end

  def calculate_form9_matching_at
    appeal.form9_match? ? (form9_matching_at || now) : nil
  end

  def calculate_already_certified
    already_certified || appeal.certified?
  end

  def calculate_vacols_data_missing
    vacols_data_missing || appeal.missing_certification_data?
  end

  def calculate_nod_matching_at
    appeal.nod_match? ? (nod_matching_at || now) : nil
  end

  def calculate_soc_matching_at
    appeal.soc_match? ? (soc_matching_at || now) : nil
  end

  def calculcate_ssocs_matching_at
    (calculate_ssocs_required && appeal.ssoc_all_match?) ? (ssocs_matching_at || now) : nil
  end

  def calculate_ssocs_required
    !appeal.ssoc_dates.empty?
  end

  class << self
    # Return existing certification only if it was not cancelled before
    def find_or_create_by_vacols_id(vacols_id)
      Certification.join_cancellations
                   .where(certification_cancellations: { certification_id: nil })
                   .find_by(vacols_id: vacols_id) || create!(vacols_id: vacols_id)
    end

    def join_cancellations
      Certification.joins("LEFT OUTER JOIN certification_cancellations ON
        certifications.id = certification_cancellations.certification_id")
    end
  end
end

app/controllers/certifications_controller.rb
require "vbms_error"

class CertificationsController < ApplicationController
  before_action :verify_access
  before_action :set_application

  def new
    # NOTE: this isn't rails-restful. certification.start! saves
    # the certification instance.
    status = certification.start!
    @form8 = certification.form8

    if verify_certification_v2_access
      render "v2", layout: "application"
      return
    end

    case status
    when :already_certified    then render "already_certified"
    when :data_missing         then render "not_ready", status: 409
    when :mismatched_documents then render "mismatched_documents"
    end
  end

  # TODO: update for certification v2- should we use hidden form params?
  def create
    # Can't use controller params in model mass assignments without whitelisting. See:
    # http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters
    params.require(:form8).permit!
    form8.update_from_string_params(params[:form8])
    form8.save_pdf!

    redirect_to certification_path(id: certification.form8.vacols_id)
  end

  def show
    render "confirm", layout: "application" if params[:confirm]
  end

  def form9_pdf
    form9 = certification.appeal.form9
    send_file(form9.serve, type: "application/pdf", disposition: "inline")
  end

  def pdf
    send_file(form8.pdf_location, type: "application/pdf", disposition: "inline")
  end

  def confirm
    @certification = Certification.find_by(vacols_id: vacols_id)

    @certification.complete!(current_user.id)

    redirect_to certification_path(id: appeal.vacols_id, confirm: true)
  end

  def set_application
    RequestStore.store[:application] = :certification
  end

  private

  def certification_cancellation
    @certification_cancellation ||= CertificationCancellation.new(certification_id: certification.id)
  end
  helper_method :certification_cancellation

  def verify_access
    verify_authorized_roles("Certify Appeal")
  end

  def verify_certification_v2_access
    return true if current_user && current_user.can?("CertificationV2")
  end

  def certification
    @certification ||= Certification.find_or_create_by_vacols_id(vacols_id)
  end

  def appeal
    @appeal ||= certification.appeal
  end
  helper_method :appeal

  def form8
    @form8 ||= certification.form8
  end
  helper_method :form8

  def vacols_id
    params[:id] || params[:vacols_id] || params[:form8][:vacols_id]
  end

  def logo_name
    "Certification"
  end
end

app/views/certifications/_cancel_certification_modal.html.erb
<%
  modal_id = "confirm-cancel-certification"
%>
<section class="cf-modal" id="<%= modal_id %>" role="alertdialog" aria-labelledby="<%= modal_id %>-title" aria-describedby="<%= modal_id %>-desc">

  <div class="cf-modal-body">
    <!-- Modal box messaging -->
    <div class="modal-container">
      <button type="button" class="cf-modal-close cf-action-closemodal">
        <%=svg_icon(:close)%>
      </button>

      <h1 class="cf-modal-title" id="<%= modal_id %>-title">Cancel Certification</h1>
      <p>
        <div class="cf-modal-segment" id="<%= modal_id %>-desc">
          Please explain why this case cannot be certified with Caseflow. Once you click <b>Cancel certification</b>, changes made to this case in Caseflow will not be saved.
        </div>
      </p>

      <%= form_for certification_cancellation,
            html: { id: "cancellation-form", class: "cf-form cf-app-segment" },
            builder: CaseflowFormBuilder do |f| %>

        <%= f.radio_buttons_field :cancellation_reason,
          values: [
            "VBMS and VACOLS dates didn't match and couldn't be changed",
            "Missing document could not be found",
            "Pending FOIA request",
            "Other"
          ],
          question_name: "cancellationReason",
          label: "Why can't be this case certified in Caseflow" %>

        <%= f.text_area :other_reason,
          question_name: "otherReason", maxlength: 2000,
          label: "Tell us more about your situation." %>

        <%= f.text_field :email,
          question_name: "email", label: "What's your VA email address?" %>

        <%= f.hidden_field :certification_id, value: certification_cancellation.certification_id  %>
          <div class="cf-modal-divider"></div>
          <div class="cf-push-row cf-modal-controls">
            <a href="#" class="cf-modal-link cf-action-closemodal cf-push-left" data-controls="#<%= modal_id%>">  &laquo; Go back
            </a>

            <button type="submit" class="cf-push-right cf-submit usa-button-secondary">Cancel certification</button>
          </div>
      <% end %>
    </div>
    <!-- /modal box messaging -->
  </div>
</section>

app/views/certifications/_document_match.html.erb
<%#
  Partial requires arguments:
  - name: user facing name of the document
  - date: VACOLS date
  - match: boolean representing if there is a matching document in VBMS
%>

<tr id="<%= name.downcase.parameterize %>-match">
  <td> <%= match ? svg_icon(:found) : svg_icon(:missing) %> </td>
  <td> <%= name %> </td>
  <td> <%= date.to_formatted_s(:short_date) %> </td>
  <td> <%= match ? date.to_formatted_s(:short_date) : "Not found" %> </td>
</tr>

app/views/certifications/already_certified.html.erb
<% content_for :page_title do certification_header("Already Certified") end %>

<div class="usa-alert usa-alert-info cf-app-segment" role="alert">
  <div class="usa-alert-body">
    <h3 class="usa-alert-heading">Appeal has already been Certified</h3>
    <p class="usa-alert-text">This case has already been certified to the Board.</p>
  </div>
</div>

<div class="cf-app-segment cf-app-segment--alt">
  <h2>Appeal has already been Certified</h2>

  <p>
    This case has already been certified to the Board. If this Case is a remand
    being re-certified to the board, Caseflow is not currently able to
    process remand cases.
  </p>
</div>

<%#= render partial: 'cancel_cert_modal' %>

app/views/certifications/confirm.html.erb
<% content_for :page_title do certification_header("Case Certified") end %>

<div id="certifications-generate" class="cf-app-msg-screen cf-app-segment cf-app-segment--alt">
  <h1 class="cf-success cf-msg-screen-heading">Congratulations!</h1>
  <h2 class="cf-msg-screen-deck"><%= appeal.veteran_full_name %>'s case [<%= appeal.vbms_id%>] has been certified.</h2>

  <ul class="cf-checklist">
      <li><span class="cf-icon-success--bg"></span> Verified documents were in eFolder</li>
      <li><span class="cf-icon-success--bg cf-success"></span> Completed and uploaded Form 8</li>
  </ul>

  <p class="cf-msg-screen-text">Way to go! You can now close this window and open another appeal in VACOLS.</p>

</div>

app/views/certifications/mismatched_documents.html.erb
<% content_for :page_title do certification_header("Mismatched Documents") end %>


<div class="cf-app-segment cf-app-segment--alt">
  <h2>Check Documents</h2>

  <div class="usa-alert usa-alert-error cf-app-segment" role="alert">
    <div class="usa-alert-body">
      <h3 class="usa-alert-heading">Cannot find documents in VBMS</h3>
      <p class="usa-alert-text">Some of the files listed in VACOLS could not be found in VBMS.</p>
    </div>
  </div>

   <div class="cf-table-wrap">
    <table class="usa-table-borderless cf-table-borderless" summary="Each row represents document mismatch">
      <caption class="usa-sr-only">
        This table compares received dates for forms stored in VACOLS and VBMS.
      </caption>

      <thead>
        <tr>
          <th><span class="usa-sr-only">Status</span>Found in VBMS?</th>
          <th>Document</th>
          <th>VACOLS date</th>
          <th>VBMS date</th>
        </tr>
      </thead>

      <tbody>
        <%= render partial: 'document_match', locals: { name: "NOD", match: appeal.nod_match?, date: appeal.nod_date } %>
        <%= render partial: 'document_match', locals: { name: "SOC", match: appeal.soc_match?, date: appeal.soc_date } %>

        <% appeal.ssoc_dates.each_index do |i| %>
          <%= render partial: 'document_match',
                     locals: { name: "SSOC #{i+1}", match: appeal.ssoc_match?(appeal.ssoc_dates[i]), date: appeal.ssoc_dates[i] } %>
        <% end %>

        <%= render partial: 'document_match', locals: { name: "Form 9", match: appeal.form9_match?, date: appeal.form9_date } %>
      </tbody>
    </table>
  </div>

  <p>
    Caseflow could not find the documents marked with an <%= svg_icon(:missing) %>
    in the appellant's eFolder. This usually happens when something doesn't match up. Try checking:
  </p>

  <ul>
    <li>The <strong>document type</strong> in VBMS to make sure it's <a href="<%= help_path %>#mismatched-documents">labeled correctly</a></li>
    <li>The <strong>document date</strong> &#8212; the date in VBMS must match the date in VACOLS</li>
  </ul>

  <p>
    Once you've made corrections,
    <button type="button" class="cf-action-refresh cf-btn-link cf-btn-link--inline">refresh this page</button>.
  </p>

  <p>
    If you can’t find the document, <a href="#confirm-cancel-certification" class="cf-action-openmodal cf-btn-link">cancel this certification.</a>
  </p>


</div>

<div class="cf-app-segment">
  <a href="#confirm-cancel-certification" class="cf-action-openmodal cf-btn-link">Cancel Certification</a>
  <button type="button" class="cf-push-right cf-action-refresh">Refresh page</button>
</div>

<%= render partial: 'cancel_certification_modal' %>

app/views/certifications/new.html.erb
<% content_for :page_title do certification_header("Complete Electronic Form 8") end %>

<script>
  $(document).ready(function() {
    window.Form8.init();
  });
</script>

<%= form_for @form8, url: { controller: "certifications", action: "create" },
                    html: { id: "form8", class: "cf-form cf-app-segment" },
                 builder: CaseflowFormBuilder do |f| %>

  <div class="usa-alert usa-alert-success cf-app-segment" role="alert">
    <div class="usa-alert-body">
      <h3 class="usa-alert-heading">All documents detected!</h3>
      <p class="usa-alert-text">The Form 9, <abbr>NOD</abbr>, <abbr>SOC</abbr> and <abbr>SSOC</abbr>s (if applicable) were found in the eFolder.</p>
    </div>
  </div>

  <div class="cf-app-segment cf-app-segment--alt">
    <header>
      <h2>Complete Electronic Form 8</h2>
      <p>Caseflow pre-fills a Form 8 for each case using data from VACOLS and VBMS.
      To finish the form, answer the remaining questions. When you are done, click <strong>Preview Completed Form 8</strong>.</p>
    </header>

    <%= f.hidden_field :vacols_id %>

    <%= f.text_field :appellant_name,
          question_number: "1A", label: "Name of Appellant (If other than veteran):" %>

    <%= f.text_field :appellant_relationship,
          question_number: "1B", label: "Relationship to Veteran:" %>

    <%= f.text_field :file_number,
          question_number: "2", label: "File Number:", readonly: true %>

    <%= f.text_field :veteran_name,
          question_number: "3", label: "Full Veteran Name:" %>

    <%= f.text_field :insurance_loan_number,
          question_number: "4", label: "Insurance file number or loan number (if pertinent):" %>

    <div class="cf-form-cond-req">
      <%= f.text_area :service_connection_for,
            question_number: "5A", label: "Service connection for:", maxlength: 5500, autoresize: true %>

      <%= f.date_field :service_connection_notification_date,
            question_number: "5B", label: "Date of notification of action appealed:" %>
    </div>

    <div class="cf-form-cond-req">
      <%= f.text_area :increased_rating_for,
            question_number: "6A", label: "Increased rating for:", maxlength: 1000, autoresize: true %>

      <%= f.date_field :increased_rating_notification_date,
            question_number: "6B", label: "Date of notification of action appealed:" %>
    </div>

    <div class="cf-form-cond-req">
      <%= f.text_area :other_for,
            question_number: "7A", label: "Other:", maxlength: 1000,
            autoresize: true %>

      <%= f.date_field :other_notification_date,
            question_number: "7B", label: "Date of notification of action appealed:" %>
    </div>

    <%= f.radio_buttons_field :representative_type,
          values: ["Attorney", "Agent", "Organization", "None", "Other"],
          question_number: "8A", part: "2", label: "Representative Type:" %>

    <%= f.text_field :representative_type_specify_other,
          question_number: "8A", part: "3", label: "Specify other representative type:", secondary: true %>

    <%= f.text_field :representative_name,
          question_number: "8A", part: "1", label: "Representative Name:" %>

    <%= f.radio_buttons_field :power_of_attorney,
          values: ["POA", "Certification that valid POA is in another VA file"], inline: true,
          question_number: "8B", part: "1", label: "What is the authority for recognizing such representative in this appeal?" %>

    <%= f.text_field :power_of_attorney_file,
          question_number: "8B", part: "2", label: "Specify file if applicable:", secondary: true %>

    <%= f.yes_no_field :agent_accredited,
          question_number: "8C", label: "Is Agent on accredited list?" %>

    <%= f.yes_no_field :form_646_of_record,
          question_number: "9A", label: "Is VA Form 646, or equivalent, of record?" %>

    <%= f.text_field :form_646_not_of_record_explanation,
          question_number: "9B", label: "Why is the Form 646 not of record?" %>

    <%= f.yes_no_field :hearing_requested,
          question_number: "10A", label: "Was BVA hearing requested?" %>

    <%= f.yes_no_field :hearing_held,
          question_number: "10B", part: "1", label: "Was the hearing held?" %>

    <%= f.yes_no_field :hearing_transcript_on_file,
          question_number: "10B", part: "2", label: "Is the hearing transcript on file?", secondary: true %>

    <%= f.text_field :hearing_requested_explanation,
          question_number: "10C", label: "If requested, but not held, explain:", maxlength: 60 %>

    <%= f.yes_no_field :contested_claims_procedures_applicable,
          question_number: "11A", label: "Are contested claims procedures applicable in this case?" %>

    <%= f.yes_no_field :contested_claims_requirements_followed,
          question_number: "11B", label: "Have the requirements of 38 U.S.C. 7105A been followed for all contested claims?" %>

    <%= f.date_field :soc_date,
          question_number: "12A", label: "Date of statement of the case furnished:" %>

    <%= f.radio_buttons_field :ssoc_required,
          values: ["Required and furnished", "Not required"],
          question_number: "12B", label: "Supplemental statement of the case:" %>

    <%= f.check_box_group record_type_check_boxes,
          question_number: "13", label: "Records to be forwarded to Board of Veterans' Appeals:" %>

    <%= f.text_field :record_other_explanation,
          question_number: "13", part: "2", label: "Specify other:", secondary: true %>

    <%= f.text_area :remarks,
          question_number: "14", label: "Remarks:", maxlength: 5500 %>

    <%= f.text_field :certifying_office,
          question_number: "15", label: "Name and location of certifying office:", readonly: true %>

    <%= f.text_field :certifying_username,
          question_number: "16", label: "Organizational elements certifying appeal:", readonly: true %>

    <%= f.text_field :certifying_official_name,
          question_number: "17A", label: "Name of certifying official:" %>

    <%= f.radio_buttons_field :certifying_official_title,
          values: ["Decision Review Officer", "Rating Specialist", "Veterans Service Representative", "Claims Assistant", "Other"],
          question_number: "17B", part: "1", label: "Title of certifying official:" %>

    <%= f.text_field :certifying_official_title_specify_other,
          question_number: "17B", part: "2", label: "Specify other title of certifying official:", secondary: true %>

    <%= f.date_field :certification_date,
          question_number: "17C", label: "Date:", readonly: true %>
  </div>

  <div class="cf-app-segment">
    <%= loading_indicator %>

    <a href="#confirm-cancel-certification" class="cf-action-openmodal cf-btn-link">Cancel Certification</a>
    <button type="submit" class="cf-push-right cf-submit">Preview Completed Form 8</button>
  </div>
<% end %>

<%= render partial: 'cancel_certification_modal' %>

app/views/certifications/not_ready.html.erb
<% content_for :page_title do certification_header("Appeal Not Ready") end %>

<div class="cf-txt-c cf-app-segment cf-app-segment--alt">
  <h1 class="cf-msg-screen-heading">Appeal is not ready for certification.</h1>
  <h2 class="cf-msg-screen-deck">Looks like this appeal is not ready for certification. Please check VACOLS.</h2>
</div>

app/views/certifications/show.html.erb
<% content_for :page_title do certification_header("Preview Electronic Form 8") end %>

<div class="cf-app-segment cf-app-segment--alt">
  <h2>Review Form 8</h2>
  <p>
    Review the completed Form 8. If the form looks correct, click <strong>Upload and certify</strong> and the form will automatically be uploaded into VBMS.
  </p>
</div>

<!-- This link is here for 508 compliance, and shouldn't be visible to sighted users. We need to allow non-sighted users to preview the Form 8. Adobe Acrobat is the accessibility standard and is used across gov't, so we'll recommend it for now. The usa-sr-only class will place an element off screen without
affecting its placement in tab order, thus making it invisible onscreen
but read out by screen readers. -->

<a class="usa-sr-only" id="sr-download-link" href="<%= pdf_certification_path(id: form8.vacols_id, time: Time.now.to_i) %>" download target="_blank">"The PDF viewer in your browser may not be accessible. Click to download the Form 8 PDF so you can preview it in a reader with accessibility features such as Adobe Acrobat.</a>
<a class="usa-sr-only" href="#certification-buttons"> If you are using a screen reader and have downloaded and verified the Form 8 PDF, click this link to skip past the browser PDF viewer to the certification buttons.</a>

<iframe aria-label="The PDF embedded here is not accessible. Please use the above link to download the PDF and view it in a PDF reader. Then use the buttons below to go back and make edits or upload and certify the document."class="cf-doc-embed cf-app-segment" title="Form8 PDF"
  src="<%= pdfjs.full_path(file: pdf_certification_path(id: form8.vacols_id, time: Time.now.to_i)) %>"></iframe>

<div class="cf-form cf-app-segment" id="certification-buttons">
  <%= loading_indicator %>

  <%= link_to "< Go back and make edits",
      new_certification_path(vacols_id: form8.vacols_id),
      class: "usa-button-gray cf-action-back cf-push-left" %>

  <%= link_to "Upload and certify",
    confirm_certification_path(id: form8.vacols_id),
    method: :post,
    class: "usa-button usa-button-blue cf-push-right cf-submit" %>
</div>

app/views/certifications/v2.html.erb
<%= react_component("Certification", props: {
  certification: @certification.to_hash
}) %>