config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create]
  resources :certifications, path_names: { new: "new/:vacols_id" } do
    get 'pdf', on: :member
    get 'form9_pdf', on: :member
    post 'confirm', on: :member
  end

  resources :certification_cancellations, only: [:show, :create]

  scope path: "/dispatch" do
    get "/", to: redirect("/dispatch/establish-claim")
    get 'missing-decision', to: 'establish_claims#unprepared_tasks'
    patch 'employee-count/:count', to: 'establish_claims#update_employee_count'

    resources :establish_claims,
              path: "/establish-claim",
              task_type: :EstablishClaim,
              only: [:index, :show] do

      patch 'assign', on: :collection
      post 'perform', on: :member
      post 'assign-existing-end-product', on: :member
      post 'review-complete', on: :member
      post 'email-complete', on: :member
      post 'no-email-complete', on: :member
      get 'pdf', on: :member
      patch 'cancel', on: :member
      put 'update-appeal', on: :member
    end
  end

  resources :document, only: [] do
    patch 'set-label', on: :member
    patch 'mark-as-read', on: :member
  end

  scope path: "/decision" do
    get "/", to: redirect("/decision/review")

    resources :annotation,
              path: "/review/annotation",
              only: [:create, :destroy, :update],
              on: :member

    resources :review,
              path: "/review",
              only: [:index] do
      get 'pdf', on: :collection
      get 'show', on: :collection
    end
  end

  patch "certifications" => "certifications#create"

  namespace :admin do
    post "establish-claim", to: "establish_claims#create"
    get "establish-claim", to: "establish_claims#show"
  end

  resources :functions, only: :index
  patch '/functions/change', to: 'functions#change'

  resources :offices, only: :index

  get "health-check", to: "health_checks#show"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get 'whats-new' => 'whats_new#show'

  get 'certification/stats(/:interval)', to: 'certification_stats#show', as: 'certification_stats'
  get 'dispatch/stats', to: 'dispatch_stats#show', as: 'dispatch_stats'
  get 'stats', to: 'stats#show'

  get "styleguide", to: "styleguide#show"

  get 'help' => 'help#show'

  root 'help#show'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  get "unauthorized" => "application#unauthorized"

  %w( 404 500 ).each do |code|
    get code, :to => "errors#show", :status_code => code
  end

  namespace :test do
    if ENV["TEST_USER_ID"]
      resources :setup, only: [:index]
      post "setup-uncertify-appeal" => "setup#uncertify_appeal"
      post "setup-appeal-location-date-reset" => "setup#appeal_location_date_reset"
      get "setup-delete-test-data" => "setup#delete_test_data"
    end

    if ApplicationController.dependencies_faked?
      resources :users, only: [:index]
      post "/set-user/:id", to: "users#set_user", as: "set_user"
      post "/set-end-products", to: "users#set_end_products", as: 'set_end_products'
    end
  end
end

app/models/dispatch_stats.rb
class DispatchStats < Caseflow::Stats
  CALCULATIONS = {
    establish_claim_identified: lambda do |range|
      EstablishClaim.where(created_at: range).count
    end,

    establish_claim_identified_full_grant: lambda do |range|
      EstablishClaim.where(created_at: range).full_grant_tasks.count
    end,

    establish_claim_identified_partial_grant_remand: lambda do |range|
      EstablishClaim.where(created_at: range).partial_grant_remand_tasks.count
    end,

    establish_claim_active_users: lambda do |range|
      EstablishClaim.where(completed_at: range).pluck(:user).uniq.count
    end,

    establish_claim_started: lambda do |range|
      EstablishClaim.where(started_at: range).count
    end,

    establish_claim_completed: lambda do |range|
      EstablishClaim.where(completed_at: range).count
    end,

    establish_claim_full_grant_completed: lambda do |range|
      EstablishClaim.where(completed_at: range).full_grant_tasks.count
    end,

    establish_claim_partial_grant_remand_completed: lambda do |range|
      EstablishClaim.where(completed_at: range).partial_grant_remand_tasks.count
    end,

    establish_claim_canceled: lambda do |range|
      EstablishClaim.where(completed_at: range).canceled.count
    end,

    establish_claim_canceled_full_grant: lambda do |range|
      EstablishClaim.where(completed_at: range).canceled.full_grant_tasks.count
    end,

    establish_claim_canceled_partial_grant_remand: lambda do |range|
      EstablishClaim.where(completed_at: range).canceled.partial_grant_remand_tasks.count
    end,

    establish_claim_completed_success: lambda do |range|
      EstablishClaim.where(completed_at: range).completed_success.count
    end,

    establish_claim_completed_success_full_grant: lambda do |range|
      EstablishClaim.where(completed_at: range).completed_success.full_grant_tasks.count
    end,

    establish_claim_completed_success_partial_grant_remand: lambda do |range|
      EstablishClaim.where(completed_at: range).completed_success.partial_grant_remand_tasks.count
    end,

    time_to_establish_claim: lambda do |range|
      DispatchStats.percentile(:time_to_establish_claim, EstablishClaim.where(completed_at: range), 95)
    end,

    median_time_to_establish_claim: lambda do |range|
      DispatchStats.percentile(:time_to_establish_claim, EstablishClaim.where(completed_at: range), 50)
    end,

    time_to_establish_claim_full_grants: lambda do |range|
      DispatchStats.percentile(:time_to_establish_claim, EstablishClaim.where(completed_at: range).full_grant_tasks, 95)
    end,

    median_time_to_establish_claim_full_grants: lambda do |range|
      DispatchStats.percentile(:time_to_establish_claim, EstablishClaim.where(completed_at: range).full_grant_tasks, 50)
    end,

    time_to_establish_claim_partial_grants_remands: lambda do |range|
      DispatchStats.percentile(:time_to_establish_claim, EstablishClaim.where(completed_at: range)
          .partial_grant_remand_tasks, 95)
    end,

    median_time_to_establish_claim_partial_grants_remands: lambda do |range|
      DispatchStats.percentile(:time_to_establish_claim, EstablishClaim.where(completed_at: range)
          .partial_grant_remand_tasks, 50)
    end
  }.freeze
end

app/controllers/dispatch_stats_controller.rb
require "json"

class DispatchStatsController < ApplicationController
  before_action :verify_authentication
  before_action :verify_access

  def show
    @dispatch_stats = {
      hourly: 0...24,
      daily: 0...30,
      weekly: 0...26,
      monthly: 0...24
    }[interval].map { |i| DispatchStats.offset(time: DispatchStats.now, interval: interval, offset: i) }
  end

  private

  def verify_access
    verify_authorized_roles("Manage Claim Establishment")
  end

  def json
    @dispatch_stats.map { |d| { key: d.range_start.to_f, value: d.values } }.to_json
  end
  helper_method :json

  def interval
    @interval ||= DispatchStats::INTERVALS.find { |i| i.to_s == params[:interval] } || :hourly
  end
  helper_method :interval

  def format_rate_stat(num, denom)
    rate_stat = if @dispatch_stats[0].values[denom] == 0 || !@dispatch_stats[0].values[num]
                  "??"
                else
                  (@dispatch_stats[0].values[num] / @dispatch_stats[0].values[denom] * 100).round
                end
    (rate_stat + "<span class=\"cf-stat-unit\">%</span>").html_safe
  end
  helper_method :format_rate_stat

  def format_time_duration_stat(seconds)
    return "?? <span class=\"cf-stat-unit\">sec</span>".html_safe unless seconds
    return "#{format('%.2f', seconds)} <span class=\"cf-stat-unit\">sec</span>".html_safe if seconds < 60
    "#{format('%.2f', seconds / 60)} <span class=\"cf-stat-unit\">min</span>".html_safe
  end
  helper_method :format_time_duration_stat
end

app/views/dispatch_stats/show.html.erb
<% content_for :page_title do %>&nbsp &gt &nbspDispatch Dashboard<% end %>

<% content_for :head do %>
    <%= javascript_include_tag 'stats' %>
    <script>
        $(function() {
            window.Dashboard.init({
                data: <%= raw json %>,
                interval: "<%= interval %>"
            })
        })
    </script>
<% end %>

<div class="cf-app-segment cf-app-segment--alt">
  <div class="cf-stats">
    <ul class="cf-tab-navigation">
      <% DispatchStats::INTERVALS.each do |interval| %>
          <li class="cf-tab <%= (@dispatch_stats[0].interval == interval) && "cf-active" %>">
          <span>
            <span>
              <%= link_to interval.to_s.capitalize, dispatch_stats_path(interval) %>
            </span>
          </span>
          </li>
      <% end %>
    </ul>

    <div class="cf-stats-section -activity">
      <h3>Establish Claim Tasks Identified <span class="data-date"></span></h3>

      <div class="cf-stat-panel data-chart" data-key="establish_claim_identified">
        <h4 class="cf-stat-title">
          All
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_identified">
          <%= @dispatch_stats[0].values[:establish_claim_identified] %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_identified_full_grant">
        <h4 class="cf-stat-title">
          Full Grants
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_identified_full_grant">
          <%= @dispatch_stats[0].values[:establish_claim_identified_full_grant] %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_identified_partial_grant_remand">
        <h4 class="cf-stat-title">
          Partial Grants & Remands
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_identified_partial_grant_remand">
          <%= @dispatch_stats[0].values[:establish_claim_identified_partial_grant_remand] %>
        </div>
      </div>
    </div>


    <div class="cf-stats-section -activity">
      <h3>Establish Claim Task Activity <span class="data-date"></span></h3>

      <div class="cf-stat-panel data-chart" data-key="establish_claim_active_users">
        <h4 class="cf-stat-title">
          Active Users
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_active_users">
          <%= @dispatch_stats[0].values[:establish_claim_active_users] %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_started">
        <h4 class="cf-stat-title">
          Establish Claim Tasks Started
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_started">
          <%= @dispatch_stats[0].values[:establish_claim_started] %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_completed">
        <h4 class="cf-stat-title">
          Establish Claim Tasks Completed
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_completed">
          <%= @dispatch_stats[0].values[:establish_claim_completed] %>
        </div>
      </div>
    </div>

    <div class="cf-stats-section -certification">
      <h3>Establish Claim Task Completion Rate <span class="data-date"></span></h3>

      <div class="cf-stat-panel data-chart" data-key="establish_claim_completed_success/establish_claim_completed">
        <h4 class="cf-stat-title">
          All
        </h4>
        <div class="cf-stat-figure data-rate" data-key="establish_claim_completed_success/establish_claim_completed">
          <%= format_rate_stat(:establish_claim_completed_success, :establish_claim_completed) %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_completed_success_full_grant/establish_claim_full_grant_completed">
        <h4 class="cf-stat-title">
          Full Grants
        </h4>
        <div class="cf-stat-figure data-rate" data-key="establish_claim_completed_success_full_grant/establish_claim_full_grant_completed">
          <%= format_rate_stat(:establish_claim_completed_success_full_grant, :establish_claim_full_grant_completed) %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_completed_success_partial_grant_remand/establish_claim_partial_grant_remand_completed">
        <h4 class="cf-stat-title">
          Partial Grants & Remands
        </h4>
        <div class="cf-stat-figure data-rate" data-key="establish_claim_completed_success_partial_grant_remand/establish_claim_partial_grant_remand_completed">
          <%= format_rate_stat(:establish_claim_completed_success_partial_grant_remand, :establish_claim_partial_grant_remand_completed) %>
        </div>
      </div>
    </div>

    <div class="cf-stats-section -timing">
      <h3>Time to Claim Establishment <span class="data-date"></span></h3>

      <div class="cf-stat-panel -toggle"
           role="button" tabindex="0"
           aria-label="Switch between median and 95th percentile statistics">
        <div class="cf-stat-option active data-chart" data-key="median_time_to_establish_claim">
          <h4 class="cf-stat-title">
            All (median)
          </h4>
          <div class="cf-stat-figure data-time" data-key="median_time_to_establish_claim">
            <%= format_time_duration_stat(@dispatch_stats[0].values[:median_time_to_establish_claim]) %>
          </div>
        </div>
        <div class="cf-stat-option data-chart" data-key="time_to_establish_claim">
          <h4 class="cf-stat-title">
            All (95th percentile)
          </h4>
          <div class="cf-stat-figure data-time" data-key="time_to_establish_claim">
            <%= format_time_duration_stat(@dispatch_stats[0].values[:time_to_establish_claim]) %>
          </div>
        </div>
      </div>
      <div class="cf-stat-panel -toggle"
           role="button" tabindex="0"
           aria-label="Switch between median and 95th percentile statistics">
        <div class="cf-stat-option active data-chart" data-key="median_time_to_establish_claim">
          <h4 class="cf-stat-title">
            Full Grants (median)
          </h4>
          <div class="cf-stat-figure data-time" data-key="median_time_to_establish_claim">
            <%= format_time_duration_stat(@dispatch_stats[0].values[:median_time_to_establish_claim]) %>
          </div>
        </div>
        <div class="cf-stat-option data-chart" data-key="time_to_establish_claim">
          <h4 class="cf-stat-title">
            Full Grants (95th percentile)
          </h4>
          <div class="cf-stat-figure data-time" data-key="time_to_establish_claim">
            <%= format_time_duration_stat(@dispatch_stats[0].values[:time_to_establish_claim]) %>
          </div>
        </div>
      </div>
      <div class="cf-stat-panel -toggle"
           role="button" tabindex="0"
           aria-label="Switch between median and 95th percentile statistics">
        <div class="cf-stat-option active data-chart" data-key="median_time_to_establish_claim">
          <h4 class="cf-stat-title">
            Partial Grants & Remands (median)
          </h4>
          <div class="cf-stat-figure data-time" data-key="median_time_to_establish_claim">
            <%= format_time_duration_stat(@dispatch_stats[0].values[:median_time_to_establish_claim]) %>
          </div>
        </div>
        <div class="cf-stat-option data-chart" data-key="time_to_establish_claim">
          <h4 class="cf-stat-title">
            Partial Grants & Remands (95th percentile)
          </h4>
          <div class="cf-stat-figure data-time" data-key="time_to_establish_claim">
            <%= format_time_duration_stat(@dispatch_stats[0].values[:time_to_establish_claim]) %>
          </div>
        </div>
      </div>
    </div>

    <div class="cf-stats-section -missing">
      <h3>Establish Claim Tasks Canceled <span class="data-date"></span></h3>

      <div class="cf-stat-panel data-chart" data-key="establish_claim_canceled">
        <h4 class="cf-stat-title">
          All
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_canceled">
          <%= @dispatch_stats[0].values[:establish_claim_canceled] %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_canceled_full_grant">
        <h4 class="cf-stat-title">
          Full Grants
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_canceled_full_grant">
          <%= @dispatch_stats[0].values[:establish_claim_canceled_full_grant] %>
        </div>
      </div>
      <div class="cf-stat-panel data-chart" data-key="establish_claim_canceled_partial_grant_remand">
        <h4 class="cf-stat-title">
          Partial Grants & Remands
        </h4>
        <div class="cf-stat-figure data-value" data-key="establish_claim_canceled_partial_grant_remand">
          <%= @dispatch_stats[0].values[:establish_claim_canceled_partial_grant_remand] %>
        </div>
      </div>
    </div>
  </div>
</div>